apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-depl
  namespace: application
  labels:
    app: product-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          image: product-catalog:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: application
  labels:
    app: product-catalog
spec:
  selector:
    app: product-catalog
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
