apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-depl
  namespace: application
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: user-api
          image: user-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: application
  labels:
    app: user-api
spec:
  selector:
    app: user-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
