apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-depl
  namespace: application
  labels:
    app: product-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: product-catalog
          image: badal1/product-catalog
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: LOKI_HOST
              value: "http://loki.monitoring.svc.cluster.local:3100"

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: application
  labels:
    app: product-catalog
spec:
  selector:
    app: product-catalog
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
