apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml # Promtail uses this to track read positions

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push 

    scrape_configs:
      - job_name: kubernetes-pods-containers
        pipeline_stages:
          - json:
              expressions:
                level: level
                message: message
                service: service
                appName: appName
          # Then, extract parsed fields into Loki labels
          - labels:
              level:
              service:
              appName:
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: __host__
          - source_labels: [__meta_kubernetes_pod_uid]
            target_label: __path__
            regex: (.+)
            replacement: /var/log/pods/$1/*.log
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app # Extracts 'app' label from pod and adds it to logs
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace # Extracts 'namespace' label
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name # Extracts 'pod_name'
          - source_labels: [__meta_kubernetes_container_name]
            target_label: container_name # Extracts 'container_name'
          - action: replace
            source_labels: [__kubernetes_node_name]
            target_label: node_name # Node name from Kubernetes metadata
          - action: replace
            source_labels: [__meta_kubernetes_pod_host_ip]
            target_label: host_ip
