apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:3.5
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"
            - "-config.expand-env=true"
          ports:
            - containerPort: 9080
              name: http-metrics
          volumeMounts:
            - name: logs
              mountPath: /var/log
              readOnly: true
            - name: loki-config
              mountPath: /etc/promtail
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: logs
          hostPath:
            path: /var/log
        - name: loki-config
          configMap:
            name: promtail-config
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
