version: "3"
services:
  video-storage-svc:
    image: badal1/video-storage-svc
    build:
      context: ./video-storage-svc
      dockerfile: Dockerfile
    container_name: video-storage-svc
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
    restart: "no"

  video-streaming-svc:
    image: 260123625978.dkr.ecr.ap-south-1.amazonaws.com/badal1/video-express
    build:
      context: ./video-streaming-svc
      dockerfile: Dockerfile
    container_name: video-streaming-svc
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage-svc
      - VIDEO_STORAGE_PORT=3000
    restart: "no"
