version: "3"
services:
  video-streaming-svc:
    image: 260123625978.dkr.ecr.ap-south-1.amazonaws.com/badal1/video-express
    build:
      context: ./video-streaming-svc
      dockerfile: Dockerfile
    container_name: video-streaming-svc
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"
