apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
              name: http-metrics
          args:
            - "-config.file=/etc/loki/config.yaml"
          volumeMounts:
            - name: loki-config-volume
              mountPath: /etc/loki
            - name: loki-data-volume
              mountPath: /loki
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: loki-config-volume
          configMap:
            name: loki-config
        - name: loki-data-volume
          persistentVolumeClaim:
            claimName: loki-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      name: http-metrics
  type: ClusterIP
